# Generated by Django 5.0.2 on 2024-02-20 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('observers', models.ManyToManyField(related_name='supervised_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
